### ISSUE TITLE
Can these bindings be used for Blazor Webassembly?

### ISSUE THREAD

**Issue by Code-Chops** [WaveEngine/OpenGL.NET#5]
Hello. I was wondering if theese bindings can be used in Blazor (Webassembly). If so, how?
Thanks in advance!

**Comment by emepetres** [comment]
Hi Daendel, yes these bindings can be used with blazor webassembly out of the box.

The tricky part is to run EGL on webassembly. For that you will need to expose the EGL api in emscripten by using the webgl library [here](https://github.com/EvergineTeam/wasm-native-libraries), reference it using the `NativeFileReference` tag in your project, and create a P/Invoke wrapper of EGL in your project.

Hope that it helps.
